# Organization Parameters

OrganizationName: untill
ClusterName: untill

# This user will be created on each node and given sudo permissions
ClusterUser: cluster

# Key Locations

PublickKey: ${HOME}/.ssh/$clusterName.pub
PrivateKey: ${HOME}/.ssh/$clusterName

## Software Versions

Docker: 18.03.0~ce-0~ubuntu

# Containers without prefix "prom/" cause of we recreates them on each host with prefix {{.OrganizationName}}. Look at
# alertmanager/Dockerfile and node-exporter/Dockerfile for more
Alertmanager: prom/alertmanager:v0.15.3
NodeExporter: stefanprodan/swarmprom-node-exporter:v0.16.0
Grafana: grafana/grafana:5.3.4
Prometheus: prom/prometheus:v2.5.0
Traefik: traefik:1.7
Cadvisor: google/cadvisor:v0.31.0

## ACME configuration

# If enabled 
#   - ACME will be used through letsencrypt provider
#   - traefik.yml is used to configure traefik, otherwise traefik-http.yml
ACMEEnabled: false

# If ACME is enabled the following paramaters are required
Domain:
Email:

#######################

# Grafana User Name
GrafanaUser: admin

# Prometheus User Name
PrometheusUser: admin

# Traefik User Name
TraefikUser: admin

## Alertmanager configuration

ChannelName: cluster
AlertmanagerUser: alertmanager