# Organization Parameters

OrganizationName: <Your Organization Name>
ClusterName: <Your Cluster Name>

# This user will be created on each node and given sudo permissions
ClusterUser: cluster

# Key Locations

PublickKey: ${HOME}/.ssh/$clusterName.pub
PrivateKey: ${HOME}/.ssh/$clusterName

# Software Versions

Docker: 17.12.0~ce-0~ubuntu
Alertmanager: prom/alertmanager:v0.15.2
NodeExporter: prom/node-exporter:v0.16.0
Prometheus: prom/prometheus:v2.4.3
Grafana: grafana/grafana:5.3.2
Traefik: traefik:1.7

## ACME configuration

# If enabled 
#   - ACME will be used through letsencrypt provider
#   - traefik.yml is used to configure traefik, otherwise traefik-http.yml
ACMEEnabled: true

# If ACME is enabled the following paramaters are required
Domain: abc
Email: cda

#######################

# Grafana User Name
GrafanaUser: admin

# Prometheus User Name
PrometheusUser: admin

# Traefik User Name
PrometheusUser: admin