version: '3'

services:
  traefik:
    image: {{.Traefik}}
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode
      - --providers.docker.watch
      - --api=true
      - --api.dashboard=true
      - --log.level=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=PathPrefix(\`/api\`) || PathPrefix(\`/dashboard\`)" 
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users={{.TraefikBasicAuth}}"
        - "traefik.http.middlewares.auth.basicauth.realm=dashboard"
        - "traefik.docker.network=webgateway"
        - "traefik.docker.lbswarm=true"
      placement:
        constraints:
          - node.role == manager

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  webgateway:
    external: true
