version: "3.5"

services:
  traefik:
    image: {{.Traefik}}
    command:
      - "--providers.consulCatalog"
      - "--providers.consulCatalog.endpoint=consul_main:8500"
      - "--providers.consulCatalog.prefix=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mon
      - consul
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.traefik == true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=PathPrefix(\`/api\`) || PathPrefix(\`/dashboard\`)" 
        - "traefik.http.routers.traefik.priority=310"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users={{.TraefikBasicAuth}}"
        - "traefik.http.middlewares.auth.basicauth.realm=dashboard"
        - "traefik.docker.network=mon"
        - "traefik.docker.lbswarm=true"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  consul:
    external: true
  mon:
    external: true
  docat:
    external: true
