route:
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    username: '{{.AlertmanagerUser}}'
    channel: '#{{.ChannelName}}'
    api_url: '{{.WebhookURL}}'
    title: '{{"{{"}}.Annotations.summary{{"}}"}}'
    text: '{{"{{"}}.Annotations.description{{"}}"}}'
