route:
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    title: '{{if .CommonAnnotations}}.CommonAnnotations.summary{{end}}'
    text: '{{if .CommonAnnotations}}.CommonAnnotations.description{{end}}'
    username: '{{.AlertmanagerUser}}'
    channel: '#{{.ChannelName}}'
    api_url: '{{.WebhookURL}}'
