# ************************************************************
#
# Organization Parameters
#
#

# This parameter will be used as a parameter to create SSH certificate
Organization: {{.OrganizationName}}

# Used to name SSH certificate
Cluster: {{.ClusterName}}

# This user will be used to create ClusterUser, after that this account will be disabled
# Password login for this user MUST be enabled
# This user MUST be able to run "sudo" commands without password
RootUser: root

# This user will be created on each node and given sudo permissions
ClusterUser: cluster

# ************************************************************
#
# Keys Location
#
#

# Default for public key is ${HOME}/.ssh/${Cluster}
#PublicKey:

# Default for private key is ${HOME}/.ssh/${Cluster}.pub
#PrivateKey:


# ************************************************************
#
# Software Versions
#
#

# Containers without prefix "prom/" cause of we recreates them on each host with prefix {{.OrganizationName}}. Look at
# alertmanager/Dockerfile and node-exporter/Dockerfile for more

Alertmanager: prom/alertmanager:v0.15.3
NodeExporter: stefanprodan/swarmprom-node-exporter:v0.16.0
Grafana: grafana/grafana:6.4.2
Prometheus: prom/prometheus:v2.5.0
Traefik: traefik:v2.0.1
Cadvisor: google/cadvisor:v0.31.0
Consul: consul:1.4.2
Elasticsearch: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
Filebeat: kindratte/filebeat:6.5.4
Kibana: docker.elastic.co/kibana/kibana-oss:6.5.4
Logstash: docker.elastic.co/logstash/logstash-oss:6.5.4
Curator: kindratte/curator:5.4

# ************************************************************
#
# Swarm networks configuration
#
#

# If true docker networks ("traefik" and "webgateway") creates with flag --opt encrypted and encrypts traffic between nodes

EncryptSwarmNetworks: true

# ************************************************************
#
# ACME configuration
#
#

# If enabled
#   - ACME will be used through letsencrypt provider
#   - traefik.yml is used to configure traefik, otherwise traefik-http.yml

#ACMEEnabled: true

# If ACME is enabled the following paramaters are required

#Domain:
#Email:

# ************************************************************
#
# Credentials
#
#

# Grafana User Name
GrafanaUser: admin

# Prometheus User Name
PrometheusUser: admin

# Traefik User Name
TraefikUser: admin

# Alertmanager user name
AlertmanagerUser: admin

# Alertmanager slack notifications settings
ChannelName: cluster
